
//API restrictions, needed to create the array
export const categories = [
  {
    url: "mmorpg.webp",
    alt: "mmorpg category",
    category: "MMORPG",
    sendTo: "/mmorpg",
  },
  {
    url: "shooter.webp",
    alt: "shooter category",
    category: "SHOOTER",
    sendTo: "/shooter",
  },
  {
    url: "strategy.webp",
    alt: "strategy category",
    category: "STRATEGY",
    sendTo: "/strategy",
  },
  { url: "moba.webp", alt: "moba category", category: "MOBA", sendTo: "/moba" },
  {
    url: "racing.webp",
    alt: "racing category",
    category: "RACING",
    sendTo: "/racing",
  },
  {
    url: "sports.webp",
    alt: "sports category",
    category: "SPORTS",
    sendTo: "/sports",
  },
  {
    url: "social.webp",
    alt: "social category",
    category: "SOCIAL",
    sendTo: "/social",
  },
  {
    url: "sandbox.webp",
    alt: "sandbox category",
    category: "SANDBOX",
    sendTo: "/sandbox",
  },
  {
    url: "open-world.webp",
    alt: "open-world category",
    category: "OPEN-WORLD",
    sendTo: "/open-world",
  },
  {
    url: "survival.webp",
    alt: "survival category",
    category: "SURVIVAL",
    sendTo: "/survival",
  },
  { url: "pvp.webp", alt: "pvp category", category: "PVP", sendTo: "/pvp" },
  { url: "pve.webp", alt: "pve category", category: "PVE", sendTo: "/pve" },
  {
    url: "pixel.webp",
    alt: "pixel category",
    category: "PIXEL",
    sendTo: "/pixel",
  },
  {
    url: "voxel.webp",
    alt: "voxel category",
    category: "VOXEL",
    sendTo: "/voxel",
  },
  {
    url: "zombie.webp",
    alt: "zombie category",
    category: "ZOMBIE",
    sendTo: "/zombie",
  },
  {
    url: "turn-based.webp",
    alt: "turn-based category",
    category: "TURN-BASED",
    sendTo: "/turn-based",
  },
  {
    url: "first-person.webp",
    alt: "first-person category",
    category: "FIRST-PERSON",
    sendTo: "/first-person",
  },
  {
    url: "third-Person.webp",
    alt: "third-Person category",
    category: "THIRD-PERSON",
    sendTo: "/third-Person",
  },
  {
    url: "top-down.webp",
    alt: "top-down category",
    category: "TOP-DOWN",
    sendTo: "/top-down",
  },
  { url: "tank.webp", alt: "tank category", category: "TANK", sendTo: "/tank" },
  {
    url: "space.webp",
    alt: "space category",
    category: "SPACE",
    sendTo: "/space",
  },
  {
    url: "sailing.webp",
    alt: "sailing category",
    category: "SAILING",
    sendTo: "/sailing",
  },
  {
    url: "side-scroller.webp",
    alt: "side-scroller category",
    category: "SIDE-SCROLLER",
    sendTo: "/side-scroller",
  },
  {
    url: "superhero.webp",
    alt: "superhero category",
    category: "SUPERHERO",
    sendTo: "/superhero",
  },
  {
    url: "permadeath.webp",
    alt: "permadeath category",
    category: "PERMADEATH",
    sendTo: "/permadeath",
  },
  { url: "card.webp", alt: "card category", category: "CARD", sendTo: "/card" },
  {
    url: "battle-royale.webp",
    alt: "battle-royale category",
    category: "BATTLE-ROYALE",
    sendTo: "/battle-royale",
  },
  { url: "mmo.webp", alt: "mmo category", category: "MMO", sendTo: "/mmo" },
  {
    url: "mmofps.webp",
    alt: "mmofps category",
    category: "MMOFPS",
    sendTo: "/mmofps",
  },
  {
    url: "mmotps.webp",
    alt: "mmotps category",
    category: "MMOTPS",
    sendTo: "/mmotps",
  },
  { url: "3d.webp", alt: "3d category", category: "3D", sendTo: "/3d" },
  { url: "2d.webp", alt: "2d category", category: "2D", sendTo: "/2d" },
  {
    url: "anime.webp",
    alt: "anime category",
    category: "ANIME",
    sendTo: "/anime",
  },
  {
    url: "fantasy.webp",
    alt: "fantasy category",
    category: "FANTASY",
    sendTo: "/fantasy",
  },
  {
    url: "sci-fi.webp",
    alt: "sci-fi category",
    category: "SCI-FI",
    sendTo: "/sci-fi",
  },
  {
    url: "fighting.webp",
    alt: "fighting category",
    category: "FIGHTING",
    sendTo: "/fighting",
  },
  {
    url: "action-rpg.webp",
    alt: "action-rpg category",
    category: "ACTION-RPG",
    sendTo: "/action-rpg",
  },
  {
    url: "action.webp",
    alt: "action category",
    category: "ACTION",
    sendTo: "/action",
  },
  {
    url: "military.webp",
    alt: "military category",
    category: "MILITARY",
    sendTo: "/military",
  },
  {
    url: "martial-arts.webp",
    alt: "martial-arts category",
    category: "MARTIAL-ARTS",
    sendTo: "/martial-arts",
  },
  {
    url: "flight.webp",
    alt: "flight category",
    category: "FLIGHT",
    sendTo: "/flight",
  },
  {
    url: "low-spec.webp",
    alt: "low-spec category",
    category: "LOW-SPEC",
    sendTo: "/low-spec",
  },
  {
    url: "tower-defense.webp",
    alt: "tower-defense category",
    category: "TOWER-DEFENSE",
    sendTo: "/tower-defense",
  },
  {
    url: "horror.webp",
    alt: "horror category",
    category: "HORROR",
    sendTo: "/horror",
  },
  {
    url: "mmorts.webp",
    alt: "mmorts category",
    category: "MMORTS",
    sendTo: "/mmorts",
  },
];
